### ISSUE TITLE
Como buscador quiero filtrar cuántos compañeros busco.

### ISSUE THREAD

**Issue by PauFargas** [4GeeksAcademy/sp50-final-project-g3#2]
# Lista de tareas

## Descripción
Esto aparecerá en la View del Usuario, puede ser en un apartado de búsqueda o en el perfil. A definir.

## Tasks:

- [ ] Definir dónde lo implementamos.
- [ ] Crear la view.
- [ ] Formulario que solo pueda entrar números.
- [ ] Definir quién puede publicarlo (solamente líder del piso?)
